### ISSUE TITLE
os.date is missing ?

### ISSUE THREAD

**Issue by tst2005** [APItools/sandbox.lua#7]
Hello,

I wonder why `os.date` is not present in the sandbox ?
Is this function is dangerous ? or is it a mistake ?

Best Regards,

**Comment by mikz** [comment]
I believe it was intentional. See the comment. https://github.com/APItools/sandbox.lua/blob/a4c0a9ad3d3e8b5326b53188b640d69de2539313/sandbox.lua#L48
Probably based on http://lua-users.org/wiki/SandBoxes
> os.date - UNSAFE - This can crash on some platforms (undocumented). For example, os.date'%v'. It is reported that this will be fixed in 5.2 or 5.1.3.

**Comment by tst2005** [comment]
Thanks !
